= Spring Boot Workshop

This workshop requires:

* git
* maven 3.2+
* JDK6+ (JDK8 if you want to have fun with lambdas)
* optional: Tomcat 8 if you want to deploy a Spring Boot war application

Note that Spring Boot itself also works with Gradle 1.12.

The slides of the session are https://speakerdeck.com/bclozel/[available on speakerdeck].

The provided applications are:

* `workshop`: main application we'll work on (web, jpa, rest repositories, security, actuator)
* `command-line` and `hello-service-auto-configuration`: showcase of a custom Spring Boot auto-configuration
* `my-webapp`: example web app that can be deployed in a Servlet 3+ container.

The following command (or the equivalent IDE command) you get the required dependencies:

    $ mvn clean package

You can check out at any time a branch that will bring you up to speed with the current step, with `stepX` the name
of the step you want to be in (i.e. step is completed and you're ready to work on the next one):

    $ git reset origin/stepX --hard


== Thanks

This workshop has been prepared by https://twitter.com/snicoll[Stéphane Nicoll] and
https://twitter.com/brianclozel[Brian Clozel].

